## Data Structures & Control Structures

In [34]:
numbers = [10,11,12,13,14]
numbers.append(15)
print(numbers)
numbers.extend([16])
print(numbers)
numbers.insert(3,13)
print(numbers)
numbers.remove(13)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.count(1))
print(numbers.index(14))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers.clear()
print(numbers)

[10, 11, 12, 13, 14, 15]
[10, 11, 12, 13, 14, 15, 16]
[10, 11, 12, 13, 13, 14, 15, 16]
[10, 11, 12, 13, 14, 15, 16]
[10, 11, 12, 13, 14, 15]
0
4
[10, 11, 12, 13, 14, 15]
[15, 14, 13, 12, 11, 10]
[]


In [26]:
students = ('Archa','Aromal','Sahil')
## It will show error, because Tuple is immmutable, we can't add,delete,modify from the tuple

In [27]:
numbers = {10,11,12,13,14,14,15,11}
numbers
## Set will remove the duplicates and print the unique values

{10, 11, 12, 13, 14, 15}

In [36]:
person = {'Name':'Shaan','Age':24,'City':'Calicut'}
person['Age'] = 26
person['email'] = 'shaan@gmail.com'
print(person)

{'Name': 'Shaan', 'Age': 26, 'City': 'Calicut', 'email': 'shaan@gmail.com'}


In [38]:
age = int(input('Enter the age'))
if age >= 18:
    print('Eligible for vote')
else:
    print('Not eligible for vot')

Enter the age 19


Eligible for vote


In [39]:
marks = float(input('Enter the marks'))
if marks >= 90:
    print('Mark: ',marks,', Grade : A')
elif marks >=75:
    print('Mark: ',marks,', Grade : B')
elif marks >=50:
    print('Mark: ',marks,', Grade : C')
elif marks < 50:
    print('Mark: ',marks,', Grade : Fail')
else:
    print('Invalid number')

Enter the marks 89


Mark:  89.0 , Grade : B


In [41]:
number = int(input('Enter the number'))
if number > 0 and number %2 ==0:
    print(f'The number {number} is positive and Even')
else:
    print(f'The number {number} is negative or 0')

Enter the number -6


The number -6 is negative or 0


## Numpy

In [12]:
import numpy as np
import pandas as pd

In [8]:
arr = np.array(5)
print(arr)
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr2 =np.array([[10,20,30],[40,50,60]])
print(arr2)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [11]:
rand = np.random.randint(0,100,size=(4,4))
print(rand)

[[27  4  0  6]
 [47 15 17 90]
 [18 15 98 91]
 [14 89 70 48]]


In [18]:
df = np.array([[10,20,30],[40,50,60],[70,80,90]])
df1 = pd.DataFrame(df,columns=['A','B','C'])
print(df1)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


## Exploring Pandas

In [29]:
dict1 = {'Name':['Nayana','Arya','Kavya','Sahil','Muhammad','Sinan','Mathew','Vishnu','Abel','Nayana'],
        'Age':[25,24,25,27,23,26,25,27,26,25],
         'City':['Kozhikode','Manathavady','Bangalore','Thrissur','Kochi','Kottayam','Kannur','Kasaragod','Alappuzha','Kozhikode'],
        'Salary':[20000,15000,25000,35000,15000,20000,np.nan,30000,25000,20000]}
data = pd.DataFrame(dict1)
print(data)

       Name  Age         City   Salary
0    Nayana   25    Kozhikode  20000.0
1      Arya   24  Manathavady  15000.0
2     Kavya   25    Bangalore  25000.0
3     Sahil   27     Thrissur  35000.0
4  Muhammad   23        Kochi  15000.0
5     Sinan   26     Kottayam  20000.0
6    Mathew   25       Kannur      NaN
7    Vishnu   27    Kasaragod  30000.0
8      Abel   26    Alappuzha  25000.0
9    Nayana   25    Kozhikode  20000.0


In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [25]:
data.describe()

,Age,Salary
count,10.000000,10.000000
mean,25.600000,25000.000000
std,1.505545,8164.965809
min,23.000000,15000.000000
25%,25.000000,20000.000000
50%,25.500000,25000.000000
75%,26.750000,28750.000000
max,28.000000,40000.000000


In [31]:
data[['Name','City']]

,Name,City
0,Nayana,Kozhikode
1,Arya,Manathavady
2,Kavya,Bangalore
3,Sahil,Thrissur
4,Muhammad,Kochi
5,Sinan,Kottayam
6,Mathew,Kannur
7,Vishnu,Kasaragod
8,Abel,Alappuzha
9,Nayana,Kozhikode


In [32]:
data.drop(columns=['City'],inplace=True)
data

,Name,Age,Salary
0,Nayana,25,20000.0
1,Arya,24,15000.0
2,Kavya,25,25000.0
3,Sahil,27,35000.0
4,Muhammad,23,15000.0
5,Sinan,26,20000.0
6,Mathew,25,NaN
7,Vishnu,27,30000.0
8,Abel,26,25000.0
9,Nayana,25,20000.0


In [33]:
data.isnull().sum()

Name      0
Age       0
Salary    1
dtype: int64

In [39]:
data.Salary.mean()

np.float64(22777.777777777777)

In [ ]:
data('Salary')

In [46]:
data['Salary'].fillna(data.Salary.mean())

0    20000.000000
1    15000.000000
2    25000.000000
3    35000.000000
4    15000.000000
5    20000.000000
6    22777.777778
7    30000.000000
8    25000.000000
9    20000.000000
Name: Salary, dtype: float64

In [47]:
data

,Name,Age,Salary
0,Nayana,25,20000.000000
1,Arya,24,15000.000000
2,Kavya,25,25000.000000
3,Sahil,27,35000.000000
4,Muhammad,23,15000.000000
5,Sinan,26,20000.000000
6,Mathew,25,22777.777778
7,Vishnu,27,30000.000000
8,Abel,26,25000.000000
9,Nayana,25,20000.000000


In [48]:
data.duplicated().sum()

np.int64(1)

In [49]:
data.drop_duplicates(inplace=True)

In [50]:
data

,Name,Age,Salary
0,Nayana,25,20000.000000
1,Arya,24,15000.000000
2,Kavya,25,25000.000000
3,Sahil,27,35000.000000
4,Muhammad,23,15000.000000
5,Sinan,26,20000.000000
6,Mathew,25,22777.777778
7,Vishnu,27,30000.000000
8,Abel,26,25000.000000
